### ISSUE TITLE
Update Login Flow

### ISSUE THREAD

**Issue by imujjwal96** [BrimeNotes/android#72]
1. Change Placeholder from `EMAIL` to `USERNAME`.
2. For the time being, avoid hashing of password using `hashText`
3. The API is now located at. http://brime.ml/ . Update the URL in the app.
Here are the routes implemented in the API till now.
![image](https://user-images.githubusercontent.com/8245662/27302929-9bffdb08-5556-11e7-85a5-172f903e79a5.png)

> 'user/login' => ['Users#login', 'post']
This means that a `post` request is sent to url `brime.ml/user/login` which calls the function `login` in `Application/Controllers/UsersController`

The code for the API can is located at https://github.com/BrimeNotes/core

**Comment by nervehammer** [comment]
@imujjwal96 please check the PR

**Comment by imujjwal96** [comment]
Closed this via edd9d34fa3494ac11cbecb69882156e62654ea5d
