### ISSUE TITLE
Client Side Validation in Login Form

### ISSUE THREAD

**Issue by syedsaadh** [BrimeNotes/android#74]
Need to implement App side Validation of login form as for now it has only Server side Validation

**Comment by imujjwal96** [comment]
@nervehammer  Can you work on this  issue?

**Comment by nervehammer** [comment]
sure @imujjwal96

**Comment by imujjwal96** [comment]
Closed via https://github.com/BrimeNotes/android/pull/75
Thanks @nervehammer . Good job!
