### ISSUE TITLE
Update UI of the About us section

### ISSUE THREAD

**Issue by imujjwal96** [BrimeNotes/android#90]
The current view of the about us section seems obnoxious and needs to be updated. It is suggestion that instead of a separate fragment/activity, a modal is used 

| Current Implementation | Sample end-result (Telegram's ui) |
|-------------------|-----------------------------|
| ![Brime](https://user-images.githubusercontent.com/8245662/28467737-749622e6-6e4e-11e7-8f82-b387b0198c63.png) | ![screenshot_20170721-195517](https://user-images.githubusercontent.com/8245662/28467975-376cc522-6e4f-11e7-9c02-bc1b4ea2f2cb.png)

**Comment by yashasingh** [comment]
@imujjwal96 Can I work on this issue ?

**Comment by imujjwal96** [comment]
Yes, you may! Cheers :)
