### ISSUE TITLE
Action on clicking Settings -> Help button

### ISSUE THREAD

**Issue by imujjwal96** [BrimeNotes/android#91]
### This is a
- [x] Feature Request
- [ ] Bug Report

### Description
The Help button in the settings panel should redirect the user to their email application with predefined 
* Email Address of Brime's contact us email id.  
* Subject
![Brime](https://user-images.githubusercontent.com/8245662/28468524-ddb1abd6-6e50-11e7-81ce-62fb5398c85d.png)

**Comment by nikhilbansal97** [comment]
@imujjwal96 I want to work on this one

**Comment by imujjwal96** [comment]
Hey @nikhilbansal97. You may work on it. All the best and cheers

**Comment by nikhilbansal97** [comment]
what is the contact us email id?

**Comment by imujjwal96** [comment]
Subject:- Feedback - BrimeNotes/android
Email:- info@brime.tk
