### ISSUE TITLE
Text labels beside floating icons

### ISSUE THREAD

**Issue by imujjwal96** [BrimeNotes/android#94]
### This is a
- [ ] Bug report
- [x] Feature request

| Current UI | Expected UI (ownCloud app sample) |
|-----------|--------------|
| ![Brime](https://user-images.githubusercontent.com/8245662/28489530-76306c8a-6ee2-11e7-8e01-44c9e3a0ceb3.png) | ![oC](https://user-images.githubusercontent.com/8245662/28489528-609cc3e6-6ee2-11e7-8d77-38ceb581f0d0.png) |

**Comment by nikhilbansal97** [comment]
@imujjwal96 I really want to work on this! Can you assign me on this issue?

**Comment by imujjwal96** [comment]
Hey @nikhilbansal97! Your comment on this issue is your assignment.

**Comment by gupta-meghna64** [comment]
Hey! I'd like to work on this issue. Can I ?

**Comment by imujjwal96** [comment]
Hello, @gupta-meghna64 There is already a pull request for this issue! Have a look at other issues and choose some to work on
